//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "edges_to_wallets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub edge_id: i32,
    pub src_wallet_id: i32,
    pub dst_wallet_id: i32,
    pub nft_wallet_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wallets::Entity",
        from = "Column::DstWalletId",
        to = "super::wallets::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Wallets3,
    #[sea_orm(
        belongs_to = "super::wallets::Entity",
        from = "Column::NftWalletId",
        to = "super::wallets::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Wallets2,
    #[sea_orm(
        belongs_to = "super::wallets::Entity",
        from = "Column::SrcWalletId",
        to = "super::wallets::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Wallets1,
}

impl ActiveModelBehavior for ActiveModel {}
