//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::edges_to_wallets::Entity as EdgesToWallets;
pub use super::tokens::Entity as Tokens;
pub use super::wallets::Entity as Wallets;
pub use super::wallets_to_tokens::Entity as WalletsToTokens;
